TRIMMOMATIC_DONE?=$(TRIMMOMATIC_OUTDIR)/.done
$(TRIMMOMATIC_DONE): $(PP_COUNT_DUPS)
	$(call _start,$(TRIMMOMATIC_OUTDIR))
		java -jar $(TRIMMOMATIC_JAR) $(TRIMMOMATIC_MODE) \
		-threads $(TRIMMOMATIC_THREADS) \
		$(TRIMMOMATIC_IN_R1) \
		$(TRIMMOMATIC_IN_R2) \
		$(TRIMMOMATIC_PAIRED_R1) \
		$(TRIMMOMATIC_NONPAIRED_R1) \
		$(TRIMMOMATIC_PAIRED_R2) \
		$(TRIMMOMATIC_NONPAIRED_R2) \
		ILLUMINACLIP:$(TRIMMOMATIC_ADAPTER_FN):$(TRIMMOMATIC_ILLUMINACLIP) \
		LEADING:$(TRIMMOMATIC_LEADING) \
		TRAILING:$(TRIMMOMATIC_TRAILING) \
		MAXINFO:$(TRIMMOMATIC_MAXINFO)
	$(_end_touch)
trimmomatic_base: $(TRIMMOMATIC_DONE)

$(PP_COUNT_TRIMMOMATIC): $(TRIMMOMATIC_DONE)
	$(_start)
	$(_md)/pl/count_fastq.pl $(TRIMMOMATIC_OUTDIR) '*' '*.fastq' no_adapters $@
	$(_end)

trimmomatic: $(PP_COUNT_TRIMMOMATIC)

