
ifeq ($(PAR_TYPE),dsub)
par:
	$(MAKE) m=gcp dsub \
	       	GCP_DSUB_SPEC_STYLE=$(PAR_SPEC_STYLE) \
	       	GCP_DSUB_RAM_GB=$(PAR_RAM_GB) \
	       	GCP_DSUB_CPU_COUNT=$(PAR_CPU_COUNT) \
	       	GCP_DSUB_BOOT_GB=$(PAR_BOOT_GB) \
	      	GCP_DSUB_DISK_TYPE=$(PAR_DISK_TYPE) \
	       	GCP_DSUB_DISK_GB=$(PAR_DISK_GB) \
		GCP_WORK_DIR=$(PAR_WORK_DIR) \
		GCP_GCR_IMAGE_PATH=$(PAR_GCR_IMAGE_PATH) \
		GCP_DSUB_NAME=$(PAR_NAME) \
		GCP_DSUB_PREEMTIBLE=$(PAR_PREEMTIBLE) \
		GCP_DSUB_ODIR_VAR=$(PAR_ODIR_VAR) \
		GCP_DSUB_TARGET=$(PAR_TARGET) \
		GCP_DSUB_WAIT=$(PAR_WAIT) \
		GCP_DSUB_UPLOAD_INTERMEDIATES=$(PAR_UPLOAD_INTERMEDIATES) \
		GCP_DSUB_DOWNLOAD_INTERMEDIATES=$(PAR_DOWNLOAD_INTERMEDIATES) \
		GCP_DSUB_MAKEFLAGS="$(PAR_MAKEFLAGS)"

par_tasks:
	$(MAKE) m=gcp dsub_tasks \
	       	GCP_DSUB_SPEC_STYLE=$(PAR_SPEC_STYLE) \
	       	GCP_DSUB_RAM_GB=$(PAR_RAM_GB) \
	       	GCP_DSUB_CPU_COUNT=$(PAR_CPU_COUNT) \
	       	GCP_DSUB_BOOT_GB=$(PAR_BOOT_GB) \
	      	GCP_DSUB_DISK_TYPE=$(PAR_DISK_TYPE) \
	       	GCP_DSUB_DISK_GB=$(PAR_DISK_GB) \
		GCP_WORK_DIR=$(PAR_WORK_DIR) \
		GCP_GCR_IMAGE_PATH=$(PAR_GCR_IMAGE_PATH) \
		GCP_DSUB_NAME=$(PAR_NAME) \
		GCP_DSUB_PREEMTIBLE=$(PAR_PREEMTIBLE) \
		GCP_DSUB_TARGET=$(PAR_TARGET) \
		GCP_DSUB_TASK_ODIR_VAR=$(PAR_TASK_ODIR_VAR) \
		GCP_DSUB_TASK_ITEM_VAR=$(PAR_TASK_ITEM_VAR) \
		GCP_DSUB_TASK_ITEM_VALS="$(PAR_TASK_ITEM_VALS)" \
		GCP_DSUB_WAIT=$(PAR_WAIT) \
		GCP_DSUB_UPLOAD_INTERMEDIATES=$(PAR_UPLOAD_INTERMEDIATES) \
		GCP_DSUB_DOWNLOAD_INTERMEDIATES=$(PAR_DOWNLOAD_INTERMEDIATES) \
		GCP_DSUB_MAKEFLAGS="$(PAR_MAKEFLAGS)"

par_tasks_table:
	$(MAKE) m=gcp dsub_tasks \
	       	GCP_DSUB_SPEC_STYLE=$(PAR_SPEC_STYLE) \
	       	GCP_DSUB_RAM_GB=$(PAR_RAM_GB) \
	       	GCP_DSUB_CPU_COUNT=$(PAR_CPU_COUNT) \
	       	GCP_DSUB_BOOT_GB=$(PAR_BOOT_GB) \
	      	GCP_DSUB_DISK_TYPE=$(PAR_DISK_TYPE) \
	       	GCP_DSUB_DISK_GB=$(PAR_DISK_GB) \
		GCP_WORK_DIR=$(PAR_WORK_DIR) \
		GCP_DSUB_NAME=$(PAR_NAME) \
		GCP_GCR_IMAGE_PATH=$(PAR_GCR_IMAGE_PATH) \
		GCP_DSUB_PREEMTIBLE=$(PAR_PREEMTIBLE) \
		GCP_DSUB_TARGET=$(PAR_TARGET) \
		GCP_DSUB_TASK_ODIR_VAR=$(PAR_TASK_ODIR_VAR) \
		GCP_DSUB_TASK_ITEM_VAR=$(PAR_TASK_ITEM_VAR) \
		GCP_DSUB_TASK_ITEM_VALS="$(call _get_field,$(PAR_TASK_ITEM_TABLE),$(PAR_TASK_ITEM_FIELD))" \
		GCP_BATCH_SIZE=$(PAR_BATCH_SIZE) \
		GCP_DSUB_WAIT=$(PAR_WAIT) \
		GCP_DSUB_UPLOAD_INTERMEDIATES=$(PAR_UPLOAD_INTERMEDIATES) \
		GCP_DSUB_DOWNLOAD_INTERMEDIATES=$(PAR_DOWNLOAD_INTERMEDIATES) \
		GCP_DSUB_MAKEFLAGS="$(PAR_MAKEFLAGS)"

par_tasks_complex:
	$(MAKE) m=gcp dsub_tasks_complex \
	       	GCP_DSUB_SPEC_STYLE=$(PAR_SPEC_STYLE) \
	       	GCP_DSUB_RAM_GB=$(PAR_RAM_GB) \
	       	GCP_DSUB_CPU_COUNT=$(PAR_CPU_COUNT) \
	       	GCP_DSUB_BOOT_GB=$(PAR_BOOT_GB) \
	      	GCP_DSUB_DISK_TYPE=$(PAR_DISK_TYPE) \
	       	GCP_DSUB_DISK_GB=$(PAR_DISK_GB) \
		GCP_WORK_DIR=$(PAR_WORK_DIR) \
		GCP_DSUB_NAME=$(PAR_NAME) \
		GCP_GCR_IMAGE_PATH=$(PAR_GCR_IMAGE_PATH) \
		GCP_DSUB_PREEMTIBLE=$(PAR_PREEMTIBLE) \
		GCP_DSUB_TARGET=$(PAR_TARGET) \
		GCP_DSUB_TASK_ITEM_TABLE=$(PAR_TASK_ITEM_TABLE) \
	       	GCP_DSUB_TASK_ITEM_VAR=$(PAR_TASK_ITEM_VAR) \
		GCP_DSUB_TASK_ODIR_VAR=$(PAR_TASK_ODIR_VAR) \
		GCP_DSUB_TASK_ITEM_VALS="$(call _get_field,$(PAR_TASK_ITEM_TABLE),$(PAR_TASK_ITEM_VAR))" \
		GCP_BATCH_SIZE=$(PAR_BATCH_SIZE) \
		GCP_DSUB_WAIT=$(PAR_WAIT) \
		GCP_DSUB_UPLOAD_INTERMEDIATES=$(PAR_UPLOAD_INTERMEDIATES) \
		GCP_DSUB_DOWNLOAD_INTERMEDIATES=$(PAR_DOWNLOAD_INTERMEDIATES) \
		GCP_DSUB_MAKEFLAGS="$(PAR_MAKEFLAGS)"

par_direct:
	$(MAKE) m=gcp dsub_direct \
	       	GCP_DSUB_SPEC_STYLE=$(PAR_SPEC_STYLE) \
	       	GCP_DSUB_RAM_GB=$(PAR_RAM_GB) \
	       	GCP_DSUB_CPU_COUNT=$(PAR_CPU_COUNT) \
	       	GCP_DSUB_BOOT_GB=$(PAR_BOOT_GB) \
	      	GCP_DSUB_DISK_TYPE=$(PAR_DISK_TYPE) \
	       	GCP_DSUB_DISK_GB=$(PAR_DISK_GB) \
		GCP_WORK_DIR=$(PAR_WORK_DIR) \
		GCP_DSUB_NAME=$(PAR_NAME) \
		GCP_GCR_IMAGE_PATH=$(PAR_GCR_IMAGE_PATH) \
		GCP_DSUB_DIRECT_ODIR_VAR=$(PAR_DIRECT_ODIR_VAR) \
		GCP_DSUB_DIRECT_COMMAND='$(subst $,$$$$,$(PAR_DIRECT_COMMAND))' \
		GCP_DSUB_DIRECT_IFN_VARS='$(PAR_DIRECT_IFN_VARS)' \
		GCP_DSUB_DIRECT_OFN_VARS='$(PAR_DIRECT_OFN_VARS)' \
		GCP_DSUB_WAIT=$(PAR_WAIT) \
		GCP_DSUB_UPLOAD_INTERMEDIATES=$(PAR_UPLOAD_INTERMEDIATES) \
		GCP_DSUB_DOWNLOAD_INTERMEDIATES=$(PAR_DOWNLOAD_INTERMEDIATES) \
		GCP_DSUB_MAKEFLAGS="$(PAR_MAKEFLAGS)"

par_delete:
	$(MAKE) m=gcp gcp_remove \
		GCP_REMOVE_PATHS="$(PAR_REMOVE_PATHS)"

par_delete_find:
	$(MAKE) m=gcp gcp_remove_find \
		GCP_REMOVE_DIR="$(PAR_REMOVE_DIR)" \
		GCP_REMOVE_NAME_PATTERN="$(PAR_REMOVE_NAME_PATTERN)"

else
par:
	$(MAKE) m=$(PAR_MODULE) $(PAR_TARGET)

par_tasks:
	$(foreach X,$(PAR_TASK_ITEM_VALS),$(MAKE) m=$(PAR_MODULE) $(PAR_TARGET) $(PAR_TASK_ITEM_VAR)=$X; $(ASSERT);)

par_tasks_table:
	$(MAKE) m=par par_tasks \
		PAR_TASK_ITEM_VALS="$(call _get_field,$(PAR_TASK_ITEM_TABLE),$(PAR_TASK_ITEM_FIELD))"

par_tasks_complex_local:
	$(foreach X,$(PAR_PARAMS),$(MAKE) m=$(PAR_MODULE) $(PAR_TARGET) $(subst :,$(__space),$X);)

par_tasks_complex:
	$(MAKE) par_tasks_complex_local \
		PAR_PARAMS="$(call _get_params,$(PAR_TASK_ITEM_TABLE),$(PAR_TASK_ITEM_VAR))"

par_direct_local:
	$(foreach i,$(PAR_DIRECT_IFN_VARS),cp $($i) /tmp/$i;)
	docker run -it --rm \
	        -v /tmp:/tmp \
	        -v /var/run/docker.sock:/var/run/docker.sock \
		$(PAR_GCR_IMAGE_PATH) \
		$(PAR_DIRECT_COMMAND)
	$(foreach o,$(PAR_DIRECT_OFN_VARS),mkdir -p $(dir $($o)); cp /tmp/$o $($o);)

par_direct:
	$(MAKE) par_direct_local \
		PAR_NAME=$(PAR_NAME) \
		GCP_GCR_IMAGE_PATH=$(PAR_GCR_IMAGE_PATH) \
		PAR_DIRECT_COMMAND='$(subst },,$(subst $${,/tmp/,$(subst ~,=,$(PAR_DIRECT_COMMAND))))' \
		PAR_DIRECT_IFN_VARS='$(PAR_DIRECT_IFN_VARS)' \
		PAR_DIRECT_OFN_VARS='$(PAR_DIRECT_OFN_VARS)'

par_delete:
	rm -rf $(PAR_REMOVE_PATHS)

par_delete_find:
	rm -rf `find $(PAR_REMOVE_DIR) -name '$(PAR_REMOVE_NAME_PATTERN)'`

endif
